services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    ports:
      - "3001:3000"
      - "5556:5555"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
volumes:
  postgres-data:
    driver: local
  cache:
    driver: local